{{ if .Values.ipBlocker.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "paxful.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
{{- end }}
